### ISSUE TITLE
Paseo Metadata not working

### ISSUE THREAD

**Issue by KarimJedda** [novasamatech/metadata-portal#1035]
I get the following error when adding Paseo network to the vault

<img width="978" alt="Screenshot 2024-10-18 at 23 07 24" src="https://github.com/user-attachments/assets/85b9221b-0308-4559-a929-42b86bc898aa">

More infos:

<img width="996" alt="Screenshot 2024-10-18 at 23 06 37" src="https://github.com/user-attachments/assets/4c75ab83-ffd6-4960-ba5b-170f31a021d8">

Thanks in advance

**Comment by pgolovkin** [comment]
Paseo chainspec and medata updated after the SS58 prefix update.
Do the following in the Polkadot Vault app:
1. Remove Paseo networks
2. Add it again

**Comment by pgolovkin** [comment]
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/0c938bf6-1a6a-443b-83c4-76d1cb564cc3">
