### ISSUE TITLE
HydraDX Metadata

### ISSUE THREAD

**Issue by Zolkapower** [novasamatech/metadata-portal#436]
Hello!
I cannot use Polkadot Vault HydraDX metadata is not available.
I get this message in the QR code location:

"The metadata for HydraDX Network is out of date. Request the new metadata version by creating a Github issue."

Can you help me with the solution?
Thank you in advance!

**Comment by pgolovkin** [comment]
Please check the Metadata portal. Latest metadata for HydraDX is there!

**Comment by Zolkapower** [comment]
> Please check the Metadata portal. Latest metadata for HydraDX is there!

Thank you for your help!
How often does it happen that the meta data is not available? I might run into a situation where I need to use the site and I don't know, it might cause some inconvenience.

**Comment by pgolovkin** [comment]
> > Please check the Metadata portal. Latest metadata for HydraDX is there!
> 
> Thank you for your help!
> How often does it happen that the metadata is not available? I might run into a situation where I need to use the site and I don't know, it might cause some inconvenience.

It may happen after the network runtime upgrade.
The Metadata portal checks and updates the Metadata every 2 hours. Then the updated QRs has to be merged and deployed so the time gap after the runtime upgrade may be from 2 to 8 hours.
