### ISSUE TITLE
Can someone update the Polkadot Vault Bittensor Metadata?

### ISSUE THREAD

**Issue by TAOVali** [novasamatech/metadata-portal#487]

**Comment by Familyman79** [comment]
I also cannot update TAO's metadata.

**Comment by pgolovkin** [comment]
The metadata was updated. Please check it https://metadata.novasama.io/?tab=1#/node-subtensor
JFYI: The Metadata portal checks all the connected chains every 2 hours. If a new metadata is available then the new QR code is created. Contributors review it and merge.

**Comment by Familyman79** [comment]
Thank you sir. You did a really good job.
