### ISSUE TITLE
Astar Network metadata update on metadata.novosama.io

### ISSUE THREAD

**Issue by Rebrizio** [novasamatech/metadata-portal#517]
The metadata for Astar Network is out of date. Request the new metadata version by creating a Github issue.

**Comment by pgolovkin** [comment]
Thanks for reporting! Closed with #515

**Comment by Rebrizio** [comment]
It seems the problem is still there.Submitted new issue #518.Could you please check?ThanksInviato da iPhoneIl giorno 9 nov 2023, alle ore 08:30, Pavel ***@***.***> ha scritto:﻿
Closed #517 as completed.
