### ISSUE TITLE
Astar Netwok metadata update on metadata.novosama.io

### ISSUE THREAD

**Issue by Rebrizio** [novasamatech/metadata-portal#518]
The metadata for Astar Network is out of date. Request the new metadata version by creating a Github issue.

**Comment by pgolovkin** [comment]
Astar metadata is available. Please check https://metadata.novasama.io/?tab=1#/astar

**Comment by Rebrizio** [comment]
ThanksInviato da iPhoneIl giorno 10 nov 2023, alle ore 06:10, Pavel ***@***.***> ha scritto:﻿
Astar metadata is available. Please check https://metadata.novasama.io/?tab=1#/astar
