### ISSUE TITLE
Request the new Bittensor metadata version 136

### ISSUE THREAD

**Issue by malapicchu** [novasamatech/metadata-portal#532]
Chainspec of Bittensor under novasama shows that the latest metadata is now 136, but I am unable to update the metadata because there is no QR code on novasama for the latest metadata. I would like to request for the new metadata version on Bittensor. 

Thanks

**Comment by pgolovkin** [comment]
Metadata updated https://metadata.novasama.io/?tab=1#/node-subtensor
