### ISSUE TITLE
bittensor metadata issue

### ISSUE THREAD

**Issue by tartraded** [novasamatech/metadata-portal#567]
<img width="1651" alt="Capture d’écran 2023-12-11 à 22 53 43" src="https://github.com/novasamatech/metadata-portal/assets/127993835/d95b5eeb-5892-48ab-a446-f7602e4ae319">
<img width="1250" alt="Capture d’écran 2023-12-11 à 22 54 48" src="https://github.com/novasamatech/metadata-portal/assets/127993835/aba4bbb1-b7b2-471d-8d7f-8d1759304d35">

**Comment by tartraded** [comment]
hi, i need to update the metadata for wallet TAO bittensor.
thank you for your help!

**Comment by pgolovkin** [comment]
New metadata is available https://metadata.novasama.io/?tab=1#/node-subtensor
Thanks for reporting!

**Comment by tartraded** [comment]
Thank you for your assistance!
