### ISSUE TITLE
EWX metadata not available

### ISSUE THREAD

**Issue by matgoodwin** [novasamatech/metadata-portal#599]
Hi,

I see Energy Web X is now in the supported list but the metadata is not available for Polkadot Vault yet. Is it possible to get this added?

**Comment by pgolovkin** [comment]
Hi,
thanks for reporting. The metadata for Energy Web X may not be added because the SS58 prefix is different in system properties and constans.
```
[2024-01-07T08:57:29Z WARN ] Failed to fetch wss://public-rpc.mainnet.energywebx.com/: Specs(Base58PrefixMismatch { specs: 64, meta: 42 })
```
I'm going to contact developers and ask to fix it.

**Comment by matgoodwin** [comment]
Hi,

It seems like the SS58 prefix was recently removed from the registry:
https://github.com/paritytech/ss58-registry/pull/195

Will this affect/stop it being used with Polkadot Vault or can support be added now?

Thanks

**Comment by pgolovkin** [comment]
@matgoodwin could you please share why and where this registry is used for? SS58 prefix for the network is hardcoded in the node code and should be changed by chain contributors in the node code.

**Comment by matgoodwin** [comment]
I may have made the incorrect assumption that this is related to the issue you were having. The comments in the PR suggest that they are not planning to use prefix 64 anymore

**Comment by pgolovkin** [comment]
Ok, got it!

**Comment by pgolovkin** [comment]
EWX metadata added https://metadata.novasama.io/?tab=0#/polkadot-ewx-parachain
