### ISSUE TITLE
paseo specs qr image outdated

### ISSUE THREAD

**Issue by hitchhooker** [novasamatech/metadata-portal#677]
https://github.com/novasamatech/metadata-portal/blob/master/public/qr/paseo_specs.png 
this network spec image outdated?

getting error that i haven't added Network when trying to sign tx on paseo.

we had maybe a month ago event on paseo where sync was restarted from scratch so most likely current qr-spec in repo is from the old network.

**Comment by pgolovkin** [comment]
Thanks for reporting! Fixed with #678
