### ISSUE TITLE
Bittensor metadata out of the date

### ISSUE THREAD

**Issue by Marosseman** [novasamatech/metadata-portal#854]
Please add new version of metadata for bittensor network.

**Comment by Marosseman** [comment]
.

**Comment by anupsadarangani** [comment]
download it from here and rename it to .png then scan it'll work

https://github.com/novasamatech/metadata-portal/pull/851/commits/b126b75a626bd228ccd092d1b2474a99fe6026db#diff-be09f7bccad958f8b7443082188045348d608d4eafdd5a33698c296482f2c42d
