### ISSUE TITLE
Update bittensor metadata 

### ISSUE THREAD

**Issue by markines92** [novasamatech/metadata-portal#855]
Hello fam. can you update bittensor metadata 152? Otherwise i can’t move my tao. Thanks!

**Comment by anupsadarangani** [comment]
download it from here and rename it to .png then scan it'll work

https://github.com/novasamatech/metadata-portal/commit/b126b75a626bd228ccd092d1b2474a99fe6026db#diff-be09f7bccad958f8b7443082188045348d608d4eafdd5a33698c296482f2c42d

**Comment by markines92** [comment]
Thanks boss!

Il sab 15 giu 2024, 21:34 anupsadarangani ***@***.***> ha
scritto:
