### ISSUE TITLE
Polkadot Vault Metadata for Bittensor outdated...

### ISSUE THREAD

**Issue by Choppama** [novasamatech/metadata-portal#856]
Hey Lads
would be nice if you guy could put up new (and actually working) metadata QR on https://metadata.novasama.io/?tab=1#/node-subtensor
Thank you !

**Comment by anupsadarangani** [comment]
download it from here and rename it to .png then scan it'll work

https://github.com/novasamatech/metadata-portal/commit/b126b75a626bd228ccd092d1b2474a99fe6026db#diff-be09f7bccad958f8b7443082188045348d608d4eafdd5a33698c296482f2c42d

**Comment by Choppama** [comment]
🤣🤣🤣🤣 nice try hindu scum

anupsadarangani ***@***.***> schrieb am Sa., 15. Juni 2024,
20:35:
